// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrp1FEjTi3mLCOvcLDSAij5snHhWA6b4w',
    appId: '1:848993028597:android:9a7353d3518926d33bb8bc',
    messagingSenderId: '848993028597',
    projectId: 'eljawda-552fd',
    storageBucket: 'eljawda-552fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEUXAIn3YFt3Bgbzff11gWxIGGyp4hWKU',
    appId: '1:848993028597:ios:eac3f0a8612d6f653bb8bc',
    messagingSenderId: '848993028597',
    projectId: 'eljawda-552fd',
    storageBucket: 'eljawda-552fd.appspot.com',
    androidClientId: '848993028597-p4kb7gobebv5h7pbvi3n9l0bfk6941qe.apps.googleusercontent.com',
    iosClientId: '848993028597-71k321kkj4b18facg30co7ofbp7350v4.apps.googleusercontent.com',
    iosBundleId: 'com.jawda.academy',
  );
}
