import 'package:elgawda_by_shay_b_haleb_new/constants/constans.dart';
import 'package:elgawda_by_shay_b_haleb_new/constants/forgetpasswordModel.dart';
import 'package:elgawda_by_shay_b_haleb_new/constants/themes.dart';
import 'package:elgawda_by_shay_b_haleb_new/localization/localization_constants.dart';
import 'package:elgawda_by_shay_b_haleb_new/secreens/authenticate/register/confirmRegister.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:elgawda_by_shay_b_haleb_new/models/utils.dart';
import 'dart:convert';

class PasswordRecovery extends StatefulWidget {
  @override
  _PasswordRecoveryState createState() => _PasswordRecoveryState();
}

class _PasswordRecoveryState extends State<PasswordRecovery> {
  final _formKey = GlobalKey<FormState>();
  bool verification = true;
  bool changePass = false;
  String? email;
  bool loading = false;

  get customColor => null;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: customColor,
        toolbarHeight: 0,
      ),
      body: SafeArea(
        child: (loading)
            ? Container(
                child: Center(child: CircularProgressIndicator()),
              )
            : ListView(
                shrinkWrap: true,
                primary: true,
                padding: EdgeInsets.symmetric(horizontal: 20, vertical: 40),
                children: [
                  LogoContainar(),
                  SizedBox(height: 40),
                  Text(
                    getTranslated(context, 'password_recovery').toString(),
                    style: AppTheme.headingColorBlue.copyWith(
                      fontSize: 15,
                      color: customColor,
                    ),
                  ),
                  Text(
                    getTranslated(context, 'valid_email').toString(),
                    style: AppTheme.subHeading.copyWith(),
                  ),
                  SizedBox(height: 40),
                  SizedBox(height: 20),
                  Padding(
                    padding: const EdgeInsets.only(left: 10, right: 10),
                    child: Form(
                      key: _formKey,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          TextFormField(
                            keyboardType: TextInputType.emailAddress,
                            style: TextStyle(color: Colors.black),
                            validator: (val) {
                              if (val!.isEmpty) {
                                return getTranslated(context, 'valid_email');
                              } else {
                                return null;
                              }
                            },
                            onChanged: (val) {
                              setState(() {
                                email = val;
                              });
                            },
                            onFieldSubmitted: (val) {
                              setState(() {
                                email = val;
                              });
                            },
                            decoration: textFormInputDecoration(
                              Icons.email,
                              getTranslated(context, 'email').toString(),
                            ),
                          ),
                          SizedBox(height: 30),
                          CustomButton(
                            text: getTranslated(context, 'send').toString(),
                            onPress: () {
                              if (_formKey.currentState!.validate()) {
                                sendForgetCode();
                              }
                            },
                          ),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
      ),
    );
  }

  // ignore: missing_return
  Future<Autogenerated?> sendForgetCode() async {
    Autogenerated? autogenerated;

    try {
      // var _body = jsonEncode(<String, String>{
      //   'email': email.toString(),
      // });
      Map<String, String> body = {
        'email': email.toString(),
      };

      var response = await http.post(Utils.SendForgetCode_URL, body: body);

      autogenerated = Autogenerated.fromJson(json.decode(response.body));

      if (autogenerated.success == true) {
        // setState(() {
        //   loading = !loading;
        // });
        Navigator.of(context).pushReplacement(
          MaterialPageRoute(
            builder: (_) => ConfirmPassword(
              email: email,
            ),
          ),
        );
      } else {
        setState(() {
          loading = !loading;
        });
        showMyDialog(
          isTrue: false,
          context: context,
          message: autogenerated.message![0],
        );
      }
    } catch (e) {
      setState(() {
        loading = !loading;
      });
      print(
          'Cash Forgtin  Password Errro ------------------------------------ ${e.toString()}');

      showMyDialog(
        isTrue: false,
        context: context,
        message: getTranslated(context, 'catchError'),
      );
    }
    return autogenerated;
  }
}
